parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        server_version: '3.15'
        charset: utf8mb4

        url: '%env(resolve:DATABASE_URL)%'

        types:
            uuid: Acme\App\Infrastructure\Persistence\Doctrine\Type\UuidType
            binary_uuid: Acme\App\Infrastructure\Persistence\Doctrine\Type\BinaryUuidType
            tag_id: Acme\App\Infrastructure\Persistence\Doctrine\Type\TagIdType
            post_id: Acme\App\Infrastructure\Persistence\Doctrine\Type\PostIdType
            user_id: Acme\App\Infrastructure\Persistence\Doctrine\Type\UserIdType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            # Each mapping must have its own 'dir' directive.
            # If we put them all in the same dir, they will not be found.
            Acme\App\Core\Component\Blog:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/blog'
                prefix: 'Acme\App\Core\Component\Blog\Domain\Entity'
                alias: Blog
            Acme\App\Core\Component\User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/user'
                prefix: 'Acme\App\Core\Component\User\Domain\Entity'
                alias: User
