parameters:

    # GraphQL API
    graphql.debug: true

    # SMS settings
    notification.sms.default_destination: '+19009990005' # So that we don't accidentally send out SMSs
    notification.sms.twilio.client.sid: 'some-dummy-TST-id'
    notification.sms.twilio.client.token: 'some-dummy-TST-token'

    # Push settings
    notification.push.one_signal.app_id: 'some-dummy-TST-id'
    notification.push.one_signal.rest_api_key: 'some-dummy-TST-key'

    # All services in this list will be added to the container used in tests
    # This is specially useful for the services provided by 3rd party bundles
    test.container.service_list:
        - 'Acme\App\Core\Component\Blog\Application\Notification\NewComment\Email\NewCommentEmailGenerator'
        - 'Acme\App\Core\Component\Blog\Application\Query\DQL\PostSlugExistsQuery'
        - 'Acme\App\Core\Component\Blog\Application\Query\DQL\FindHighestPostSlugSuffixQuery'
        - 'Acme\App\Core\Component\Blog\Application\Query\DQL\FindLatestPostsQuery'
        - 'Acme\App\Core\Component\Blog\Application\Query\DQL\FindPostsBySearchRequestQuery'
        - 'Acme\App\Core\Component\Blog\Application\Query\CommentListQueryInterface'
        - 'Acme\App\Core\Component\Blog\Application\Query\FindAuthorIdByCommentIdQueryInterface'
        - 'Acme\App\Core\Component\Blog\Application\Query\FindAuthorIdByPostIdQueryInterface'
        - 'Acme\App\Core\Component\Blog\Application\Query\PostQueryInterface'
        - 'Acme\App\Core\Component\Blog\Application\Query\TagListQueryInterface'
        - 'Acme\App\Core\Component\Blog\Application\Repository\DQL\PostRepository'
        - 'Acme\App\Core\Component\User\Application\Repository\DQL\UserRepository'
        - 'Acme\App\Core\Port\Lock\LockManagerInterface'
        - 'Acme\App\Core\Port\Persistence\DQL\DqlQueryBuilderInterface'
        - 'Acme\App\Core\Port\Persistence\QueryServiceInterface'
        - 'Acme\App\Core\Port\Persistence\QueryServiceRouterInterface'
        - 'Acme\App\Core\Port\Persistence\TransactionServiceInterface'
        - 'Acme\App\Core\Port\Router\UrlGeneratorInterface'
        - 'Acme\App\Core\Port\TemplateEngine\TemplateEngineInterface'
        - 'Acme\App\Core\Port\Translation\TranslatorInterface'
        - 'Acme\App\Infrastructure\Persistence\Doctrine\DqlPersistenceService'
        - 'Acme\App\Presentation\Console\Component\User\AddUserCommand'
        - 'Acme\App\Presentation\Web\Core\Port\FlashMessage\FlashMessageServiceInterface'
        - 'Acme\App\Presentation\Web\Core\Port\Form\FormFactoryInterface'
        - 'Acme\App\Presentation\Web\Core\Port\Response\ResponseFactoryInterface'
        - 'Acme\App\Test\Framework\Decorator\EmailCollectorEmailerDecorator'
        - 'Doctrine\ORM\EntityManagerInterface'
        - 'Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'
        - 'session'
